# Generated by Django 3.1.7 on 2021-03-03 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedstocksdb',
            name='market',
        ),
    ]
