# Generated by Django 3.1.7 on 2021-03-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditWallSteetBetsHotDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RedditWallStreetBetsStocksDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_ticker', models.TextField(max_length=5, unique=True)),
                ('stock_mentions', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='RedditStocksDB',
        ),
    ]
