# Generated by Django 3.1.7 on 2021-03-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0002_auto_20210316_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redditwallsteetbetshotdb',
            name='author',
        ),
        migrations.AlterField(
            model_name='redditwallstreetbetsstocksdb',
            name='stock_ticker',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
