# Generated by Django 3.1.7 on 2021-03-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0003_auto_20210316_1329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RedditWallSteetBetsHotDB',
        ),
    ]
