# Generated by Django 3.1.7 on 2021-03-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0004_delete_redditwallsteetbetshotdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditWallSteetBetsHotDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=250)),
                ('upvotes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('up_votes_ratio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('url', models.URLField()),
                ('date_created', models.TextField()),
                ('time_created', models.TextField()),
            ],
        ),
    ]
