# Generated by Django 3.1.7 on 2021-03-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0005_redditwallsteetbetshotdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RedditWallSteetBetsHotDB',
            new_name='RedditWallStreetBetsHotDB',
        ),
    ]
