# Generated by Django 3.1.7 on 2021-03-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0006_auto_20210316_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditWallStreetBetsNewDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=250, null=True)),
                ('upvotes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('up_votes_ratio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('url', models.URLField()),
                ('date_created', models.TextField()),
                ('time_created', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RedditWallStreetBetsTopDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=250, null=True)),
                ('upvotes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('up_votes_ratio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('url', models.URLField()),
                ('date_created', models.TextField()),
                ('time_created', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='redditwallstreetbetshotdb',
            name='author',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
